version: '3'

services:
  database:
    image: postgres:10.6
    volumes:
      - ${DATA_PATH:-./data}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=identity
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - 8180:8080
    volumes:
      - ./demo/keycloak:/tmp
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/master.json